# 4_additional_UCEs_from_genomes/environment.yml
name: uce_add
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - mafft            # alignment program
  - seqkit           # fast FASTA/FASTQ manipulations
  - seqmagick        # format conversion (brings in Biopython)
  - emboss           # <- adds consambig for IUPAC consensus
