# 4_additional_UCEs_from_genomes/environment.yml
name: uce_add
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - mafft            
  - seqkit           
  - seqmagick        
  - emboss           
  - astral-tree    